baseurl               = "https://pujol.io"
languageCode          = "en-us"
title                 = "Alexandre Pujol"
theme                 = "identity"
preserveTaxonomyNames = true
disableRSS            = true
watch                 = true
paginate              = 3



[params]
    description1      = "Ph.D. Student in computer security at"
    description2      = "University College Dublin (Ireland)"
    description3      = "and dual degree engineer manager."
    keywords          = "Alexandre,Pujol,Polytech Marseille,KedgeBS,computer science,engineer,Businnes School,dual degree,Master in Management,computer security,security,linux,cloud"

[params.intro.pic]
    src               = "/assets/images/avatar.jpg"
    circle            = true
    imperfect         = false
    width             = ""
    alt               = "Alexandre Pujol"



[[menu.main]]
    name              = "My GPG Keys"
    url               = "/keys/"
    identifier        = "fa fa-key"
    weight            = 1

[[menu.main]]
    name              = "My Publications"
    url               = "/pub/"
    identifier        = "fa fa-leanpub"
    weight            = 2



[social]
    gpgkey            = ""
    pub               = ""
    gitlab            = "pujol"
    github            = "alexandrepujol"
    linkedin          = "alexandrepujol"
    googlescholar     = "LMPIGiYAAAAJ&hl"
    twitter           = ""
    bitbucket         = ""
    jsfiddle          = ""
    codepen           = ""
    foursquare        = ""
    dribbble          = ""
    deviantart        = ""
    behance           = ""
    flickr            = ""
    instagram         = ""
    youtube           = ""
    vimeo             = ""
    vine              = ""
    medium            = ""
    wordpress         = ""
    tumblr            = ""
    xing              = ""
    slideshare        = ""
    stackoverflow     = ""
    reddit            = ""
    pinterest         = ""
    googleplus        = ""
    facebook          = ""
    facebook_admin    = ""
    twitter_domain    = ""
    email             = "alexandre@pujol.io"
