baseurl               = "https://pujol.io"
languageCode          = "en-US"
title                 = "Alexandre Pujol"
theme                 = "sustain"
preserveTaxonomyNames = true
disableRSS            = true
watch                 = true
paginate              = 3
googleAnalytics       = "UA-104152570-1"

#
# Parameters
#
[params]
  avatar      = "avatar.png"
  author      = "Alexandre Pujol"
  description = "Ph.D. Student in computer security at University College Dublin (Ireland)."
  keywords    = "Alexandre,Pujol,Phd Student,research,UCD,University College Dublin,Polytech Marseille,KedgeBS,computer science,engineer,Businnes School,dual degree,Master in Management,computer security,security,linux,cloud"
  source      = "https://github.com/roddhjav/pujol.io"
  fingerprint = "6C84 7129 A72F 6144 E629  9C92 CE0E AD7F 0718 0C35"
  base        = "https://pujol.io"

[permalinks]
  post = "/:year/:month/:day/:slug"

#
# Menu
#
[[menu.main]]
  name = "GPG Keys"
  identifier = "keys"
  weight = 100
  url = "/keys"

[[menu.main]]
  name = "Blog"
  weight = 200
  identifier = "blog"
  url = "/blog"

[[menu.main]]
  name = "Research"
  identifier = "research"
  weight = 300
  url = "/research"

[[menu.main]]
  name = "Publications"
  identifier = "pub"
  weight = 400
  url = "/pub"

# [[menu.main]]
#   name = "Projects"
#   identifier = "projects"
#   weight = 500
#   url = "/projects"

#
# Social
#
[Social]
  gitlab        = "roddhjav"
  github        = "roddhjav"
  twitter       = "roddhjav"
  keybase       = "roddhjav"
  mastodon      = "https://mamot.fr/@roddhjav"
  linkedIn      = "alexandrepujol"
  googlescholar = "LMPIGiYAAAAJ&hl"
  email         = "alexandre@pujol.io"
