baseurl               = "https://pujol.io"
languageCode          = "en-US"
title                 = "Alexandre Pujol"
theme                 = "sustain"
preserveTaxonomyNames = true
disableRSS            = true
watch                 = true
paginate              = 3

#
# Parameters
#
[params]
  avatar      = "avatar.png"
  author      = "Alexandre Pujol"
  description = "Ph.D. Student in computer security at University College Dublin (Ireland)."
  keywords    = "Alexandre,Pujol,Phd Student,research,UCD,University College Dublin,Polytech Marseille,KedgeBS,computer science,engineer,Businnes School,dual degree,Master in Management,computer security,security,linux,cloud"
  source      = "https://gitlab.com/roddhjav/roddhjav.gitlab.io"
  fingerprint = "E17E AB91 1D01 BEDA B150  BBBF CAFE 9215 B58C 7C3B"

[permalinks]
  post = "/:year/:month/:day/:slug"

#
# Menu
#
[[menu.main]]
  name = "GPG Keys"
  identifier = "keys"
  weight = 100
  url = "/keys"


[[menu.main]]
  name = "Research"
  identifier = "research"
  weight = 300
  url = "/research"

[[menu.main]]
  name = "Publications"
  identifier = "pub"
  weight = 400
  url = "/pub"


#
# Social
#
[Social]
  gitlab        = "roddhjav"
  github        = "roddhjav"
  twitter       = "roddhjav"
  mastodon      = "https://mamot.fr/@roddhjav"
  linkedIn      = "alexandrepujol"
  googlescholar = "LMPIGiYAAAAJ&hl"
  email         = "alexandre@pujol.io"
